language: node_js
node_js:
  - 8.10.0
addons:
  chrome: stable
  hostname: localhost
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - yarn start &
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test:unit
  - yarn test:int
  - yarn test:e2e
  - yarn build
